# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'challenge-ss' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for challenge-ss
  pod 'Kingfisher', '~> 5.0'

  target 'challenge-ssTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'challenge-ssUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
